require 'yaml'
require 'aws-sdk'

desc "sam build"
task :build do
  system('sam build --use-container')
end

desc "sam package"
task :package do
  system("sam package \
    --output-template-file #{environment}-packaged.yaml \
    --s3-bucket #{bucket_name}")
end

desc "sam deploy"
task :deploy do

end

def environment
  ENV["environment"] || 'development'
end

def project_name
  `pwd`.gsub(/^.*\//,'').chop
end

def bucket_name
  project_name + '-deployment'
end
